### ISSUE TITLE
FPAT Appraisal Follow-up

### ISSUE THREAD

**Issue by esarks** [esarks/Royal-Palms-Accounting#14]
Ian Wright
Cell: 352-942-6845

**Comment by esarks** [comment]
Called, to voicemail.
Left text requesting info be sent to paul@themarshalls.us

**Comment by esarks** [comment]
Ian responded.  On his way home, he said he'd send the report.

**Comment by esarks** [comment]
Ian texted.  The report hasn't gone through full review yet.  He will check on Monday.

**Comment by esarks** [comment]
Talked to Ian.  Still awaiting review.  He said he'd try to push it through.

**Comment by esarks** [comment]
The invoice submitted is not the same as the quote.  Marty will follow-up.

https://github.com/esarks/Royal-Palms-Accounting/blob/master/Invoices/2018-08/INV_VAL1811889_2566.pdf

**Comment by esarks** [comment]
This invoice is approved for payment by Marty.

**Comment by esarks** [comment]
Bill Pay submitted through Regions.

**Comment by martypetty** [comment]
Thanks!

*Marty*

2018 IS THE YEAR OF THE ROCKSTARIT'S TIME TO FOCUS ON YOUR PEOPLE!

Marty Petty
President & CEO


727.580.7317
*marty@mpettygroup.com <marty@mpettygroup.com>*
http://www.mpettygroup.com/

7235 First Ave. S., Suite A
Gulfport, FL  33707

The information contained in this e-mail is confidential and may be
privileged.  If you are not the intended recipient, then (i) any
dissemination, distribution or reproduction of this email is strictly
prohibited; and (ii) please notify us by email of the error in transmission
and delete it from your computer immediately.

Thank you.

**Comment by esarks** [comment]
Closed
